import { styled } from './styled'
import {
  createScaleVariant,
  createSpaceVariant,
  createCssVariant,
} from './utils'

export const Box = styled('div', {
  boxSizing: 'border-box',
  variants: {
    fontFamily: createScaleVariant('fonts', 'fontFamily'),
    fontSize: createScaleVariant('fontSizes', 'fontSize'),
    fontWeight: createScaleVariant('fontWeights', 'fontWeight'),
    lineHeight: createScaleVariant('lineHeights', 'lineHeight'),
    letterSpacing: createScaleVariant('letterSpacings', 'letterSpacing'),

    borderRadius: createScaleVariant('radii', 'borderRadius'),
    boxShadow: createScaleVariant('shadows', 'boxShadow'),
    bg: createScaleVariant('colors', 'backgroundColor'),
    color: createScaleVariant('colors', 'color'),
    borderColor: createScaleVariant('colors', 'borderColor'),
    zIndex: createScaleVariant('zIndices', `zIndex`),
    // Why not size? size has other means in descendant components
    boxSize: createScaleVariant('sizes', 'width', 'height'),
    width: createScaleVariant('sizes', 'width'),
    minWidth: createScaleVariant('sizes', 'minWidth'),
    maxWidth: createScaleVariant('sizes', 'maxWidth'),
    height: createScaleVariant('sizes', 'height'),
    minHeight: createScaleVariant('sizes', 'minHeight'),
    maxHeight: createScaleVariant('sizes', 'maxHeight'),
    m: createSpaceVariant('margin'),
    mx: createSpaceVariant('marginLeft', 'marginRight'),
    ml: createSpaceVariant('marginLeft'),
    mr: createSpaceVariant('marginRight'),
    my: createSpaceVariant('marginTop', 'marginBottom'),
    mt: createSpaceVariant('marginTop'),
    mb: createSpaceVariant('marginBottom'),
    p: createSpaceVariant('padding'),
    px: createSpaceVariant('paddingLeft', 'paddingRight'),
    pl: createSpaceVariant('paddingLeft'),
    pr: createSpaceVariant('paddingRight'),
    py: createSpaceVariant('paddingTop', 'paddingBottom'),
    pt: createSpaceVariant('paddingTop'),
    pb: createSpaceVariant('paddingBottom'),
    // inset: createSpaceVariant('left', 'right', 'top', 'bottom'),
    left: createSpaceVariant('left'),
    right: createSpaceVariant('right'),
    top: createSpaceVariant('top'),
    bottom: createSpaceVariant('bottom'),
    display: createCssVariant('display', [
      'block',
      'contents',
      'flex',
      'grid',
      'inline',
      'inline-block',
      'inline-flex',
      'none',
    ]),
    position: createCssVariant('position', [
      'absolute',
      'fixed',
      'relative',
      'static',
      'sticky',
    ]),
    overflow: createCssVariant('overflow', [
      'auto',
      'clip',
      'hidden',
      'scroll',
      'visible',
    ]),
    overflowX: createCssVariant('overflowX', [
      'auto',
      'clip',
      'hidden',
      'scroll',
      'visible',
    ]),
    overflowY: createCssVariant('overflowY', [
      'auto',
      'clip',
      'hidden',
      'scroll',
      'visible',
    ]),
    textAlign: createCssVariant('textAlign', ['center', 'left', 'right']),
    float: createCssVariant('float', ['none', 'left', 'right']),
    isolation: createCssVariant('isolation', ['auto', 'isolate']),
    flexShrink: {
      '0': {
        flexShrink: 0,
      },
      '1': {
        flexShrink: 1,
      },
    },
  },
})
